"""
Global Pytest Test Configuration & Hermetic Harness.
Auto-generated by preflight-test-engineer.
"""

import pytest
import os
from typing import Generator, Any

@pytest.fixture(autouse=True)
def isolate_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    """Hermetic isolation: sets safe mock environment variables and prevents leaks."""
    monkeypatch.setenv("TESTING", "true")
    monkeypatch.setenv("ENV", "test")
    monkeypatch.setenv("DATABASE_URL", "sqlite:///:memory:")

@pytest.fixture
def mock_external_api(monkeypatch: pytest.MonkeyPatch) -> Generator[None, None, None]:
    """Guards against unintentional external network calls during hermetic testing."""
    # Custom socket/request interceptor mock
    yield
