#!/usr/bin/env python3
"""
Pre-Flight Test Suite Scaffolder CLI.
Deterministically scaffolds a standardized, hermetic /tests/ architecture
for Python and TypeScript/React projects based on AST analysis.
"""

import sys
import os
import re
import json
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional

# Import local analyzer if available
try:
    from analyze_codebase import run_analysis, detect_stack
except ImportError:
    # Inline fallback detection if called standalone
    from .analyze_codebase import run_analysis, detect_stack

PYTHON_CONFTEST_TEMPLATE = '''"""
Global Pytest Test Configuration & Hermetic Harness.
Auto-generated by preflight-test-engineer.
"""

import pytest
import os
from typing import Generator, Any

@pytest.fixture(autouse=True)
def isolate_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    """Hermetic isolation: sets safe mock environment variables and prevents leaks."""
    monkeypatch.setenv("TESTING", "true")
    monkeypatch.setenv("ENV", "test")
    monkeypatch.setenv("DATABASE_URL", "sqlite:///:memory:")

@pytest.fixture
def mock_external_api(monkeypatch: pytest.MonkeyPatch) -> Generator[None, None, None]:
    """Guards against unintentional external network calls during hermetic testing."""
    # Custom socket/request interceptor mock
    yield
'''

PYTEST_INI_TEMPLATE = '''[pytest]
minversion = 7.0
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test* *Suite
python_functions = test_*
addopts = -ra -q --strict-markers --strict-config
markers =
    unit: Fast, deterministic unit tests isolated from external dependencies
    integration: Multi-module or service-boundary integration tests
    smoke: Pre-flight sanity tests verifying environment & importability
    slow: Tests requiring extended execution time
'''

PYTHON_SMOKE_TEST_TEMPLATE = '''"""
Pre-Flight Smoke & Sanity Tests.
Verifies module importability, syntax integrity, and basic execution safety.
"""

import importlib
import pytest
from pathlib import Path

def test_preflight_environment_variables() -> None:
    """Verifies test environment configuration."""
    import os
    assert os.getenv("TESTING") == "true"
'''

PYTHON_FIXTURES_FACTORY_TEMPLATE = '''"""
Hermetic Test Data Factories & Mock Generators.
"""

from typing import Dict, Any

def make_sample_payload(**overrides: Any) -> Dict[str, Any]:
    """Generates a standard test dictionary payload with optional overrides."""
    payload = {
        "id": "test-id-12345",
        "name": "Sample Entity",
        "status": "active",
        "created_at": "2026-01-01T00:00:00Z"
    }
    payload.update(overrides)
    return payload
'''

TS_SETUP_TEMPLATE = '''/**
 * Global Test Harness Setup & DOM Polyfills.
 * Auto-generated by preflight-test-engineer.
 */

// Global mock isolation and cleanup
beforeEach(() => {
  // Reset all mocks between tests
  if (typeof vi !== 'undefined') {
    vi.clearAllMocks();
  } else if (typeof jest !== 'undefined') {
    jest.clearAllMocks();
  }
});

// Guard against unhandled network requests
afterEach(() => {
  // Hermetic teardown
});
'''

VITEST_CONFIG_TEMPLATE = '''import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: '%ENVIRONMENT%',
    setupFiles: ['./tests/setup.ts'],
    include: ['tests/**/*.{test,spec}.{ts,tsx,js,jsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: ['node_modules/', 'tests/']
    }
  }
});
'''

TS_SMOKE_TEST_TEMPLATE = '''/**
 * Pre-Flight Smoke & Sanity Tests.
 * Verifies environment integrity and runtime exports.
 */

import { describe, it, expect } from 'vitest';

describe('Pre-Flight Smoke Sanity Suite', () => {
  it('should verify test runner environment is active', () => {
    // Vitest sets NODE_ENV to 'test'. Asserting on it means this smoke test
    // actually fails when the harness is misconfigured, which is the only
    // reason to have a smoke test at all.
    expect(process.env.NODE_ENV).toBe('test');
  });
});
'''

TS_FIXTURES_TEMPLATE = '''/**
 * Hermetic Test Fixtures & Factories.
 */

export interface SampleEntity {
  id: string;
  name: string;
  status: 'active' | 'inactive';
}

export function createMockEntity(overrides: Partial<SampleEntity> = {}): SampleEntity {
  return {
    id: 'mock-id-123',
    name: 'Test Entity',
    status: 'active',
    ...overrides
  };
}
'''

def generate_python_unit_test(module_name: str, functions: List[str], classes: List[Dict[str, Any]]) -> str:
    """
    Generate a structured Python unit test file with parameterized cases
    and edge tests.

    Scaffolded tests fail until someone writes them. An `assert True` body
    makes an empty suite report green, which is worse than having no suite
    at all: it produces a passing CI badge over zero verification, and
    nothing ever prompts anyone to finish the job. `pytest.fail` keeps the
    scaffold honest -- the suite stays red until the assertions are real.
    """
    lines = [
        f'"""',
        f'Unit tests for module: {module_name}',
        f'Auto-scaffolded by preflight-test-engineer.',
        f'"""',
        f'',
        f'import pytest',
        f'',
    ]

    for cls in classes:
        cname = cls["name"]
        lines.append(f'class Test{cname}:')
        lines.append(f'    """Test suite for {cname}."""')
        lines.append(f'')
        lines.append(f'    def test_{cname.lower()}_initialization(self) -> None:')
        lines.append(f'        """Verifies {cname} instantiates properly."""')
        lines.append(f'        # TODO: Instantiate with valid test arguments')
        lines.append(f'        pytest.fail("Unimplemented: {cname} instantiation test")')
        lines.append(f'')
        for m in cls.get("methods", []):
            lines.append(f'    def test_{m}_happy_path(self) -> None:')
            lines.append(f'        """Verifies {m} behavior under expected conditions."""')
            lines.append(f'        # TODO: Implement happy path assertion')
            lines.append(f'        pytest.fail("Unimplemented: {m} happy path")')
            lines.append(f'')
            lines.append(f'    def test_{m}_edge_cases(self) -> None:')
            lines.append(f'        """Verifies {m} handles boundary conditions and errors gracefully."""')
            lines.append(f'        # TODO: Test None/empty inputs, invalid types, boundary numbers')
            lines.append(f'        pytest.fail("Unimplemented: {m} edge cases")')
            lines.append(f'')

    for fn in functions:
        lines.append(f'def test_{fn}_success() -> None:')
        lines.append(f'    """Verifies {fn} execution with valid inputs."""')
        lines.append(f'    # TODO: Call {fn} and assert expected output')
        lines.append(f'    pytest.fail("Unimplemented: {fn} success case")')
        lines.append(f'')
        lines.append(f'def test_{fn}_boundary_and_negative_inputs() -> None:')
        lines.append(f'    """Verifies {fn} handles empty, None, and edge inputs."""')
        lines.append(f'    # TODO: Call {fn} with boundary arguments')
        lines.append(f'    pytest.fail("Unimplemented: {fn} boundary cases")')
        lines.append(f'')

    if not classes and not functions:
        lines.append(f'def test_{module_name}_placeholder() -> None:')
        lines.append(f'    """Placeholder test verifying {module_name} module loading."""')
        lines.append(f'    pytest.fail("Unimplemented: no functions or classes detected in {module_name}")')
        lines.append(f'')

    return "\n".join(lines)

def generate_ts_unit_test(module_name: str, functions: List[str]) -> str:
    """Generates a TypeScript unit test file with describe/it blocks and boundary cases."""
    lines = [
        f'/**',
        f' * Unit tests for module: {module_name}',
        f' * Auto-scaffolded by preflight-test-engineer.',
        f' */',
        f'',
        f"import {{ describe, it, expect }} from 'vitest';",
        f'',
        f"describe('{module_name} Unit Suite', () => {{",
    ]

    for fn in functions:
        lines.append(f"  describe('{fn}()', () => {{")
        lines.append(f"    it('should return expected result with standard inputs', () => {{")
        lines.append(f"      // TODO: Test happy path for {fn}")
        lines.append(f"      throw new Error('Unimplemented: {fn} happy path');")
        lines.append(f"    }});")
        lines.append(f"")
        lines.append(f"    it('should handle edge cases (null, empty, boundary)', () => {{")
        lines.append(f"      // TODO: Test negative and boundary cases for {fn}")
        lines.append(f"      throw new Error('Unimplemented: {fn} edge cases');")
        lines.append(f"    }});")
        lines.append(f"  }});")
        lines.append(f"")

    if not functions:
        lines.append(f"  it('should load module correctly', () => {{")
        lines.append(f"    throw new Error('Unimplemented: no exported functions detected');")
        lines.append(f"  }});")

    lines.append(f"}});")
    return "\n".join(lines)

def generate_react_component_test(component_name: str) -> str:
    """Generates a React component test with React Testing Library, user-event, and accessibility checks."""
    return f'''/**
 * Component test for <{component_name} />
 * Auto-scaffolded by preflight-test-engineer.
 */

import React from 'react';
import {{ describe, it, expect }} from 'vitest';
// import {{ render, screen }} from '@testing-library/react';
// import userEvent from '@testing-library/user-event';

describe('<{component_name} /> Component', () => {{
  it('renders without crashing', () => {{
    // render(<{component_name} />);
    throw new Error('Unimplemented: <{component_name} /> render test');
  }});

  it('handles user interactions and event propagation', async () => {{
    // const user = userEvent.setup();
    // render(<{component_name} />);
    throw new Error('Unimplemented: <{component_name} /> interaction test');
  }});

  it('renders with accessible roles and attributes', () => {{
    // Verify accessibility contracts
    throw new Error('Unimplemented: <{component_name} /> accessibility test');
  }});
}});
'''

def scaffold(target_dir: Path, force: bool = False, dry_run: bool = False) -> Dict[str, Any]:
    """Executes the test suite scaffolding process."""
    analysis = run_analysis(target_dir)
    stack = analysis["stack"]
    created_files = []
    skipped_files = []

    tests_root = target_dir / "tests"
    
    # Subdirectories
    subdirs = ["unit", "integration", "fixtures", "smoke"]
    if stack["is_react"] or stack["is_typescript"]:
        subdirs.append("components")

    for sd in subdirs:
        dir_path = tests_root / sd
        if not dry_run:
            dir_path.mkdir(parents=True, exist_ok=True)

    # 1. Python Scaffolding
    if stack["is_python"]:
        # conftest.py
        conftest_path = tests_root / "conftest.py"
        if not conftest_path.exists() or force:
            if not dry_run:
                conftest_path.write_text(PYTHON_CONFTEST_TEMPLATE, encoding="utf-8")
            created_files.append(str(conftest_path.relative_to(target_dir)))
        else:
            skipped_files.append(str(conftest_path.relative_to(target_dir)))

        # pytest.ini
        pytest_ini = target_dir / "pytest.ini"
        pyproject_toml = target_dir / "pyproject.toml"
        if not pytest_ini.exists() and not (pyproject_toml.exists() and "[tool.pytest" in pyproject_toml.read_text(encoding="utf-8", errors="ignore")):
            if not dry_run:
                pytest_ini.write_text(PYTEST_INI_TEMPLATE, encoding="utf-8")
            created_files.append("pytest.ini")

        # Smoke test
        smoke_path = tests_root / "smoke" / "test_preflight_smoke.py"
        if not smoke_path.exists() or force:
            if not dry_run:
                smoke_path.write_text(PYTHON_SMOKE_TEST_TEMPLATE, encoding="utf-8")
            created_files.append(str(smoke_path.relative_to(target_dir)))

        # Fixtures factory
        factories_path = tests_root / "fixtures" / "factories.py"
        if not factories_path.exists() or force:
            if not dry_run:
                factories_path.write_text(PYTHON_FIXTURES_FACTORY_TEMPLATE, encoding="utf-8")
            created_files.append(str(factories_path.relative_to(target_dir)))

        # Unit tests for discovered modules
        for mod in analysis["source_analysis"]["python_modules"]:
            if not mod["has_test"]:
                mod_name = Path(mod["rel_path"]).stem
                target_test = tests_root / "unit" / f"test_{mod_name}.py"
                if not target_test.exists() or force:
                    content = generate_python_unit_test(
                        mod_name, 
                        [f["name"] for f in mod["functions"]], 
                        mod["classes"]
                    )
                    if not dry_run:
                        target_test.write_text(content, encoding="utf-8")
                    created_files.append(str(target_test.relative_to(target_dir)))

    # 2. TypeScript / React Scaffolding
    if stack["is_typescript"] or stack["is_javascript"]:
        # setup.ts / setup.js
        ext = "ts" if stack["is_typescript"] else "js"
        setup_path = tests_root / f"setup.{ext}"
        if not setup_path.exists() or force:
            if not dry_run:
                setup_path.write_text(TS_SETUP_TEMPLATE, encoding="utf-8")
            created_files.append(str(setup_path.relative_to(target_dir)))

        # vitest.config.ts / jest config
        vitest_cfg = target_dir / f"vitest.config.{ext}"
        if not vitest_cfg.exists() and not (target_dir / "jest.config.js").exists():
            env_type = "jsdom" if stack["is_react"] else "node"
            cfg_content = VITEST_CONFIG_TEMPLATE.replace("%ENVIRONMENT%", env_type)
            if not dry_run:
                vitest_cfg.write_text(cfg_content, encoding="utf-8")
            created_files.append(f"vitest.config.{ext}")

        # Smoke test
        ts_smoke_path = tests_root / "smoke" / f"preflight_smoke.test.{ext}"
        if not ts_smoke_path.exists() or force:
            if not dry_run:
                ts_smoke_path.write_text(TS_SMOKE_TEST_TEMPLATE, encoding="utf-8")
            created_files.append(str(ts_smoke_path.relative_to(target_dir)))

        # Fixtures factory
        ts_fixtures_path = tests_root / "fixtures" / f"factories.{ext}"
        if not ts_fixtures_path.exists() or force:
            if not dry_run:
                ts_fixtures_path.write_text(TS_FIXTURES_TEMPLATE, encoding="utf-8")
            created_files.append(str(ts_fixtures_path.relative_to(target_dir)))

        # Component & Unit tests for discovered modules
        for mod in analysis["source_analysis"]["ts_js_modules"]:
            if not mod["has_test"]:
                mod_stem = Path(mod["rel_path"]).stem
                mod_ext = Path(mod["rel_path"]).suffix
                
                # Check if it has React components
                if mod["components"]:
                    for comp in mod["components"]:
                        comp_test_path = tests_root / "components" / f"{comp}.test{mod_ext}"
                        if not comp_test_path.exists() or force:
                            comp_content = generate_react_component_test(comp)
                            if not dry_run:
                                comp_test_path.write_text(comp_content, encoding="utf-8")
                            created_files.append(str(comp_test_path.relative_to(target_dir)))
                else:
                    unit_test_path = tests_root / "unit" / f"{mod_stem}.test{mod_ext}"
                    if not unit_test_path.exists() or force:
                        unit_content = generate_ts_unit_test(mod_stem, mod["functions"])
                        if not dry_run:
                            unit_test_path.write_text(unit_content, encoding="utf-8")
                        created_files.append(str(unit_test_path.relative_to(target_dir)))

    return {
        "target_dir": str(target_dir.resolve()),
        "created_files": created_files,
        "skipped_files": skipped_files,
        "dry_run": dry_run,
        "stack": stack
    }

def main():
    if sys.stdout.encoding != 'utf-8':
        try:
            sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        except Exception:
            pass

    parser = argparse.ArgumentParser(description="Scaffold a hermetic, complete test suite into /tests/.")
    parser.add_argument("--target-dir", type=str, default=".", help="Target repository directory (default: current dir).")
    parser.add_argument("--force", action="store_true", help="Overwrite existing test files.")
    parser.add_argument("--dry-run", action="store_true", help="Show proposed files without writing.")
    args = parser.parse_args()

    target = Path(args.target_dir).resolve()
    if not target.exists():
        print(f"[ERROR] Target directory '{target}' does not exist.", file=sys.stderr)
        sys.exit(1)

    print("=" * 72)
    print(" 🛠️  [TEST SCAFFOLDER] Scaffolding Standardized /tests/ Harness")
    print("=" * 72)
    
    result = scaffold(target, force=args.force, dry_run=args.dry_run)

    mode_str = "[DRY-RUN] Would create:" if args.dry_run else "[SCAFFOLDED] Created files:"
    print(f"\n {mode_str}")
    for cf in result["created_files"]:
        print(f"  ✨ {cf}")

    if result["skipped_files"]:
        print(f"\n [SKIPPED] Existing files preserved (use --force to overwrite):")
        for sf in result["skipped_files"]:
            print(f"  ℹ️  {sf}")

    print("\n" + "=" * 72)
    print(f" Total: {len(result['created_files'])} test files generated.")
    print("=" * 72)

if __name__ == "__main__":
    main()
